### ISSUE TITLE
Functions are attached to self/this so do not permit overriding

### ISSUE THREAD

**Issue by ncote** [h5p/h5p-question#1]
For example, in question.js: 

``` javascript
self.addButton = function (id, ...
```

This prevents easy overriding in a "subclass", since the function is attached to the instance and not the prototype.  If we look at ImageHotspotQuestion, in contrast, all functions are attached to the prototype.  To override addButton then, we would have to define it on the instance, and also save a reference to the parent function if we needed to delegate to it.

**Comment by icc** [comment]
Scoping is the only way to have _private_ variables in JavaScript, it's not a very uncommon practice and it can make overriding harder. Not having _private_ variables will make it difficult to do small changes without changing the API, which in turn means a new version. I.e. it makes for a cleaner interface.
Performance wise it should make much of a difference in modern browsers.

I'm not sure what you mean by "subclass". If you could post an example or try explaining what you're trying to do, we could then possibly adapt the Question class to better fit your needs. Also, feel free to create pull requests and suggest changes.
