### ISSUE TITLE
Support audio integration similar to video and image

### ISSUE THREAD

**Issue by alexglausch** [h5p/h5p-question#3]
I want to prequalify a pull request related to the following:

User story:

As an developer I want support for the integration of  h5p-audio for my question type so that i can provide the possiblity to add an audio file.

With today's functionality I only have support for h5p-image and h5p-video.

UX:
Not relevant 

Technical solution:
I want to add a function setAudio similiar to setImage and setVideo that creates an instance of h5p-audio player and uses the params from the h5p-audio editor.

**Comment by otacke** [comment]
Hi Alex!

I think this would be a welcome contribution. I started to implement the exactly same feature some time ago as a private project. It seems I have not yer uploaded it to github, I probably should search my dev systems for it and make the code public.

I have not worked on it for some time, but I in fact ran into some UX issues that I don't remember exactly at the moment.

What do you think? Should we work on this together? It'll still be a spare time project for me though and I don't know how much time I can invest.

**Comment by alexglausch** [comment]
Hey Oliver,

that would be great! It would be of course very helpful if you can find your customizations but you don't need to spend much time on it. I could come up with a solution and provide it to you for reviewing :).

I also would like to create issues on h5p-multi-choice and h5p-true-false, which use h5p-question, to extend the media type selector by audio. May it be that you have conctact to any contributors of these libs?

**Comment by otacke** [comment]
Hi @alexglausch!

I have found the repository and merged it with the latest release version of H5P Question. It's in a [branch in my repository](https://github.com/otacke/h5p-question/tree/add_setAudio). Have not checked if it still works, but feel free to use it if it's useful for you.

**Comment by alexglausch** [comment]
Hey Oliver,
thank you for your efforts :)!
I tested your solution with the latest version of h5p-multi-choice and it works quite well. 
How do we want to proceed ? Is it possible to create a pull request right away?

**Comment by otacke** [comment]
There's probably a reason why I didn't do that already :-) Have not put any TODO tags into the code, and this stuff has been idling on my harddrive for quite some time now, so I don't remember. Bummer.

I can only assume that some browsers caused problems, but I can have a look at it this evening. Anyway, definitely good to know that you didn't find any obvious issues.

**Comment by otacke** [comment]
@alexglausch Hmm, I don't think so. The only updates that Audio received has recently were changes to the language files. I'll have a look at the _setaudio_ code, check it in IE11 and some other browsers (I have access to BrowserStack) and see if I can remember why I didn't file in a pull request.

**Comment by otacke** [comment]
@alexglausch Sorry, I probably won't come around to it today. I'm still in the office and have work to do.

**Comment by alexglausch** [comment]
@otacke No problem :). No need to push yourself. If I can be of any help just tell me.

**Comment by otacke** [comment]
@alexglausch OK :-) Worst case should be Friday.

I left a todo marker in the code, so feel free to have a look at resizing -- there might be some problems (on some browsers?) and that's probably why I didn't create a pull request.

**Comment by alexglausch** [comment]
@otacke Yah, i recognized that marker but i was wondering if that is really an issue for the audio player because from what i see in the h5p-audio code the player only fits the audio icon to match the wrapper size on resize but does not trigger a resize on the parent.
I checked the behaviour in Chrome, Firefox, Egde, IE11, Safari 10.1, iOS Safari 9.  The only issue i found is that on Safari that the height of the player isnt set correctly but i think that should be tackled by the inheriting library. The audio player is always embedded correctly.

**Comment by otacke** [comment]
@alexglausch I see. I cannot recall what I had in mind back then :-) Maybe I wanted to have a look at H5P Audio as well. Good to know that you checked that already! Thanks!

**Comment by otacke** [comment]
Hi @alexglausch!
I've checked the implementation using [https://github.com/otacke/h5p-true-false/tree/add_setaudio](https://github.com/otacke/h5p-true-false/tree/add_setaudio) and found what was bugging me. It was not the sizing of the button.

It was in fact the fixed height of 32px which would cause trouble on mobile Safari where the user agent style for audio elements has a height of 39px and the top would be cut off. Similarly, the height in IE11 would be "wrong" or at least different to what it is standalone H5P Audio. I fixed that cleanly in the latest push. Maybe you could lend it a second pair of eyes.

What I'd like to do is to override the library settings for Audio in semantics, so fit-to-width and the full player mode would be the default, but that's not possible without changing the core of H5P first :-/ But if/as soon that's done, it might be handy for other content types, too, that e.g. don't want to offer all the editor options of a library that they use.

Anyway ... If you don't find any other problems, we should create a pull request. What do you think about that?

**Comment by alexglausch** [comment]
Hey @otacke 
Thanks for your efforts! 
Looks good to me :). The styling of the wrapper for the audio element should be part of the inheriting library.

I like your idea to make library semantics overridable.

When the pull request is accepted i also would like to make pull requests for h5p-audio and h5p-true-false so that the change can be of use. How do you think I should proceed?

**Comment by otacke** [comment]
@alexglausch I agree with your thoughts about the styling, but the [height is set to 100 % deliberately in H5P.Audio](https://github.com/h5p/h5p-audio/blob/master/scripts/audio.js#L172-L174) if the library is not used standalone as in our case. It might have been introduced earlier and become obsolete meanwhile, but I don't know. That's why I merely reset the height value in h5p-question, because here it's definitely counter-productive.

I guess to be sure, we would have to check with manifold browsers if setting the height of the audio element to 100% isn't necessary in any of the content types that use H5P.Audio as a library. It might just be a remnant, just like the flash based flow player that could probably be thrown out.

Changing True/False or similar content types should be straight forward [just like my test branch](https://github.com/otacke/h5p-true-false/tree/add_setaudio). Change, pull request, done.

With Audio, it might depend on what you're planning to do. If it's not just minor stuff, it's probably a good idea to ask beforehand if there's anything you should keep in mind. For comparison: I'd consider the changes made here in H5P Question as minor. They don't interfere with other functionality, are just a couple of lines, etc.

**Comment by otacke** [comment]
@alexglausch Just got some extra information: Setting the height is probably not necessary anymore, but there are lots of Course Presentations using Audio inside boxes. If Audio is set to use the full player, then removing the height of 100 % will not harm the height of the player, but the position may change. In a nutshell: The code will have to remain in Audio to not break existing content, and it seems H5P Question will have to deal with it like I did. I'll create the pull request in both our names.

By the way: What are you planning for Audio?

**Comment by alexglausch** [comment]
@otacke thank you for the informations. And thank you very much for creating the pull request in our both names, though it feels like you did all the work :). I'm curious if it's gonna pass in the first try.

**Comment by otacke** [comment]
@alexglausch You tested and asked good questions, so you're welcome! I'll close this issue, and you can [follow the pull request progress](https://github.com/h5p/h5p-question/pull/4).
